version: '3.2'
services:
  # sonarqube:
  #   build:
  #     context: sonarqube/
  #   ports:
  #     - 9000:9000
  #   container_name: sonarqube
  #   environment:
  #     - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresdb:5432/sonar
  #   volumes:
  #     - ./data/sonar/sonarqube/conf:/opt/sonarqube/conf
  #     - ./data/sonar/sonarqube/data:/opt/sonarqube/data
  #     - ./data/sonar/sonarqube/extensions:/opt/sonarqube/extensions

  # postgresdb:
  #   build:
  #     context: postgres/
  #   #image: postgres
  #   container_name: postgresdb
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #   volumes:
  #     - ./data/postgresql:/var/lib/postgresql
  #     # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
  #     - ./data/postgresql_data:/var/lib/postgresql/data

  jenkins:
    build:
      context: jenkins/
    #privileged: true
    #user: root
    ports:
      - 8080:8080
      #- 50000:50000
    container_name: jenkins
    # environment:
    #   - DOCKER_OPTS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock"
    volumes:
      - ./data/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
      #- ${DOCKER_PATH}:/usr/bin/docker:ro
    # depends_on:
    #   - sonarqube

  gitlab-ce:
    build:
      context: gitlab-ce/
    restart: always
    hostname: 'ci-cd.dockerdonegal.ie'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://ci-cd.dockerdonegal.ie'
    ports:
      - '80:80'
    #  - '22:22'
    container_name: gitlab-ce
    volumes:
      - './data/gitlab/config:/etc/gitlab'
      - './data/gitlab/logs:/var/log/gitlab'
      - './data/gitlab/data:/var/opt/gitlab'

networks: 
  default:
    external:
      name: dd_ninja